global:
  exporters:
    e1: # give a name you like, will not be used
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "/tmp/perf-00.json"

SIFT-IVF-PQ:
    datapath: "./data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "ivf_pq"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"buckets_count":50,"base_quantization_type":"fp32","coarse_cluster_count":100,"fine_cluster_count":100,"filter_nsq":32,"train_points_count":500000,"pq_train_points_count":100000}}'
    search_params: '{"ivf_pq":{"scan_buckets_count":10,"search_coarse_count":30,"search_fine_count":100,"filter_topk":150,"window_size":20}}'
    index_path: "./index/sift-128-euclidean/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: false